server:
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerceDB
    username: root
    password: aspire@123
    tomcat.max-wait: 20000
    tomcat.max-active: 50
    tomcat.max-idle: 20
    tomcat.min-idle: 15
    validationQuery: SELECT 1
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  jpa:
    generate-ddl: true

management:
  server:
    port: 8764
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"
eureka:
  client:
    serviceUrl: 
      defaultZone:  http://localhost:8762/eureka/
